plugins/redmine_people/config/routes.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2018 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :people do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email, :avatar
      post :bulk_edit, :bulk_update, :send_mails, :add_manager
      delete :bulk_destroy
      get 'calendar' => 'people_calendars#index'
      resources :holidays, :except => :show, :controller => :people_holidays, :as => :people_holidays
    end
    member do
      get :manager
      get :autocomplete_for_manager
      delete :destroy_avatar
      get 'tabs/:tab' => 'people#show', :as => "tabs"
      get 'load_tab' => 'people#load_tab', :as => "load_tab"
      delete "remove_subordinate" => "people#remove_subordinate" , :as => "remove_subordinate"
    end
    resources :people_rates, except: [:index, :show]
end

resources :departments do
  member do
    get :autocomplete_for_person
    post :add_people
    delete :remove_person
    get 'tabs/:tab' => 'departments#show', :as => "tabs"
    get 'load_tab' => 'departments#load_tab', :as => "load_tab"
  end
end

resources :people_settings do
  collection do
    get :autocomplete_for_user
  end
end

resources :people_queries

plugins/redmine_people/app/models/people_rate.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2018 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

class PeopleRate < ActiveRecord::Base
  include Redmine::SafeAttributes

  COST_RATE = 'cost_rate'.freeze
  BILL_RATE = 'bill_rate'.freeze
  RATE_TYPES = [COST_RATE, BILL_RATE]

  belongs_to :project
  belongs_to :person, foreign_key: :user_id

  validates :rate_type, :rate, :from_date, :user_id, presence: true
  validates :rate_type, inclusion: { in: RATE_TYPES }
  validates :rate, numericality: true
  validates :rate_type, uniqueness: { scope: [:user_id, :from_date, :project_id] }

  attr_protected :id if ActiveRecord::VERSION::MAJOR <= 4
  safe_attributes 'rate_type', 'rate', 'currency', 'from_date', 'project_id', 'user_id'

  scope :cost_rates, -> { where(rate_type: COST_RATE).order('from_date desc') }
  scope :bill_rates, -> { where(rate_type: BILL_RATE).order('from_date desc') }

  def self.prefix(type)
    { COST_RATE => 'cost', BILL_RATE => 'bill' }[type]
  end

  def self.current_rate(rates, date = User.current.today)
    rates.sort { |a, b| b.from_date <=> a.from_date }
      .each { |rate| return rate if rate.from_date <= date }

    nil
  end

  def self.current_rates(rates, date = User.current.today)
    rates.group_by(&:project_id).map { |project_id, _rates| current_rate(_rates, date) }.compact
  end

  def self.cost_rate_for(person, date = User.current.today, project = nil)
    current_rate(person.rates.cost_rates.where(project_id: project), date).try(:rate)
  end

  def self.bill_rate_for(person, date = User.current.today, project = nil)
    current_rate(person.rates.bill_rates.where(project_id: project), date).try(:rate)
  end
end

plugins/redmine_people/app/controllers/people_rates_controller.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2018 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

class PeopleRatesController < ApplicationController
  before_action :require_login
  before_action :set_person
  before_action :check_permissions
  before_action :set_people_rate, only: [:show, :edit, :update, :destroy]

  def new
    @people_rate = PeopleRate.new(from_date: Date.today)
  end

  def edit
  end

  def create
    @people_rate = PeopleRate.new(user_id: @person.id)
    @people_rate.safe_attributes = params[:people_rate]

    if @people_rate.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to tabs_person_path(@person, 'rates')
    else
      render :new
    end
  end

  def update
    @people_rate.safe_attributes = params[:people_rate]
    if @people_rate.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to tabs_person_path(@person, 'rates')
    else
      render :edit
    end
  end

  def destroy
    @people_rate.destroy
    redirect_to tabs_person_path(@person, 'rates'), notice: l(:notice_people_rate_successfully_destroyed)
  end

  private
    def set_people_rate
      @people_rate = PeopleRate.find(params[:id])
    end

    def check_permissions
      render_403 unless User.current.allowed_people_to?(:edit_rates, @person)
    end
end

plugins/redmine_people/app/helpers/people_rates_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2018 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

module PeopleRatesHelper
end

plugins/redmine_people/app/views/people_rates/_form.html.erb
<%= labelled_fields_for :people_rate, @people_rate do |f| %>
  <p><%= f.select :rate_type, PeopleRate::RATE_TYPES.map { |type| [l("label_people_#{type}"), type] }, required: true %></p>
  <p>
    <%= f.text_field :rate, required: true %>
  </p>
  <p>
    <% if Redmine::VERSION.to_s < '3.0' %>
      <%= f.text_field :from_date, type: :date, required: true %>
    <% else %>
      <%= f.date_field :from_date, required: true %>
    <% end %>
    <%= calendar_for('people_rate_from_date') %>
  </p>
  <p>
    <%= f.select :project_id, project_tree_options_for_select(Project.all, include_blank: l(:label_project_all), selected: @people_rate.project), required: true %>
  </p>
<% end %>

plugins/redmine_people/app/views/people_rates/_index.html.erb
<div class="contextual">
  <%= link_to l(:button_add), new_person_people_rate_path(@person), class: 'icon icon-add' %>
</div>
<h3><%= l(:label_people_rates_history) %></h3>

<% if @person.rates.blank? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <div class="autoscroll">
    <table class="list issues">
      <thead>
      <tr>
        <th><%= l(:field_from_date) %></th>
        <th><%= l(:field_project) %></th>
        <th><%= l(:field_rate) %></th>
        <th></th>
      </tr>
      </thead>

      <tbody>
        <%= render partial: 'people_rates/rates_list', locals: { rates_collector: @rates_collector, type: PeopleRate::COST_RATE } %>
        <%= render partial: 'people_rates/rates_list', locals: { rates_collector: @rates_collector, type: PeopleRate::BILL_RATE } %>
      </tbody>
    </table>
  </div>
<% end %>

plugins/redmine_people/app/views/people_rates/_rates_list.html.erb
<% prefix = PeopleRate.prefix(type) %>
<% rates = @person.rates.send("#{prefix}_rates") %>
<% current_rates = PeopleRate.current_rates(rates) %>
<% default_rate = rates_collector.send("default_#{prefix}_rate") %>

<tr class="group open">
  <td colspan="10">
    <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
    <span class="name"><%= l("label_people_#{prefix}_rates") %></span> <span class="count"><%= rates.size %></span>
    <% if default_rate.present? %>
      <span class="totals">
        <span class="total-for-estimated-hours">
          <span><%= l("label_people_default_#{prefix}_rate") %>: </span>
          <span class="value"><%= rate_to_currency(default_rate) %></span>
        </span>
      </span>
    <% end %>
    <a href="#" onclick="toggleAllRowGroups(this); return false;" class="toggle-all"><%= "#{l(:button_collapse_all)}/#{l(:button_expand_all)}" %></a>
  </td>
</tr>

<% rates.each do |people_rate| %>
  <tr class="<%= cycle('odd', 'even') %>" style="<%= current_rates.include?(people_rate) ? '' : 'color: #aaa;' %>">
    <td><%= format_date people_rate.from_date %></td>
    <% if people_rate.project.present? %>
      <td><%= people_rate.project %></td>
    <% else %>
      <td style="font-style: italic ;"><%= l(:label_default) %></td>
    <% end %>
    <td><%= rate_to_currency(people_rate.rate) %></td>
    <td>
      <%= link_to l(:button_edit), edit_person_people_rate_path(@person, people_rate), class: 'icon icon-edit' %>
      <%= link_to l(:button_delete), person_people_rate_path(@person, people_rate), class: 'icon icon-del', data: { confirm: l(:text_are_you_sure) }, method: :delete %>
    </td>
  </tr>
<% end %>

plugins/redmine_people/app/views/people_rates/edit.html.erb
<h2><%=l(:label_people_rate_edit)%></h2>

<%= labelled_form_for @people_rate, url: person_people_rate_path(@person, @people_rate), html: { id: 'people_rate', multipart: true } do |f| %>
  <%= error_messages_for 'people_rate' %>
  <div class="box tabular">
    <div id="all_attributes">
      <%= render partial: 'form', locals: { f: f } %>
    </div>
  </div>

  <%= submit_tag l(:button_update) %>
<% end %>

plugins/redmine_people/app/views/people_rates/new.html.erb
<h2><%=l(:label_people_rate_new)%></h2>

<%= labelled_form_for @people_rate, url: person_people_rates_path(@person), html: { id: 'people_rate', multipart: true } do |f| %>
  <%= error_messages_for 'people_rate' %>
  <div class="box tabular">
    <div id="all_attributes">
      <%= render partial: 'form', locals: { f: f } %>
    </div>
  </div>

  <%= submit_tag l(:button_create) %>
<% end %>